### ISSUE TITLE
点击 “语音识别（语音对话后点击）” 报错 pydantic_core._pydantic_core.ValidationError: 1 validation error for LogMessage

### ISSUE THREAD

**Issue by gg22mm** [Kedreamix/Linly-Talker#102]
点击 “语音识别（语音对话后点击）” 报错
![图片](https://github.com/user-attachments/assets/7f916aaf-678b-4268-96b6-a736f2f4774f)
![图片](https://github.com/user-attachments/assets/346bb3cc-ccbf-4a53-94e4-50b247c47e5f)

---------------------如下：
Traceback (most recent call last):
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/paddle/www/txsb/api/Linly-Talker-main/src/cost_time.py", line 7, in wrapper
    result = func(*args, **kwargs)
  File "/paddle/www/txsb/api/Linly-Talker-main/webui.py", line 59, in Asr
    gr.Warning("ASR Error: ", e)
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/helpers.py", line 1304, in Warning
    log_message(message, level="warning", duration=duration, visible=visible)
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/helpers.py", line 1278, in log_message
    blocks._queue.log_message(
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/gradio/queueing.py", line 387, in log_message
    log_message = LogMessage(
  File "/home/data/miniconda3/envs/linly/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for LogMessage
duration
  Input should be a valid number [type=float_type, input_value=TypeError('expected np.ndarray (got NoneType)'), input_type=TypeError]
    For further information visit https://errors.pydantic.dev/2.9/v/float_type

**Comment by gg22mm** [comment]
看了视频，是麦克风而已~~
