### ISSUE TITLE
CG客户端运行webui.py报错

### ISSUE THREAD

**Issue by Heaverno** [Kedreamix/Linly-Talker#107]
通过CG客户端拉取的v4镜像，在jupyterlab里运行webui.py报错
网上说这种报错一般因为cuda pytorch等版本对不上，但是镜像里会出现这种问题吗
win11就装了显卡驱动和docker desktop，wsl-ubuntu根据CG客户端教程装了cg-client和nvidia-docker
镜像里nvcc报告cuda版本为11.8.89
```
PaddleTTS Error:  No module named 'paddlespeech'
如果使用PaddleTTS，请先安装PaddleTTS环境
pip install -r requirements_paddle.txt
默认不使用LLM模型，直接回复问题，同时减少显存占用！
GPT_SoVITS导入失败，原因： Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found
使用GPT-SoVITS语音克隆前需要安装对应的环境，请执行 pip install -r VITS/requirements_vits.txt
2024-09-30 16:40:58,172 - modelscope - INFO - PyTorch version 2.0.0+cu118 Found.
2024-09-30 16:40:58,172 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2024-09-30 16:40:58,605 - modelscope - INFO - Updating the files for the changes of local files, first time updating will take longer time! Please wait till updating done!
2024-09-30 16:40:58,620 - modelscope - INFO - AST-Scanning the path "/root/miniconda3/lib/python3.8/site-packages/modelscope" with the following sub folders ['models', 'metrics', 'pipelines', 'preprocessors', 'trainers', 'msdatasets', 'exporters']
CosyVoice导入失败，原因： During ast indexing the file /root/miniconda3/lib/python3.8/site-packages/modelscope/models/audio/aec/layers/activations.py, a related error excepted in the file /root/miniconda3/lib/python3.8/site-packages/modelscope/utils/ast_utils.py at line: 151: "attr = getattr(node, field)" with error msg: "AttributeError: 'ClassDef' object has no attribute 'type_params'", please double check the origin file /root/miniconda3/lib/python3.8/site-packages/modelscope/models/audio/aec/layers/activations.py to see whether the file is correctly edited.
使用CosyVoice语音克隆前需要安装对应的环境
GPT-SoVITS 加载失败: name 'GPT_SoVITS' is not defined
如果使用VITS，请先下载GPT-SoVITS模型并安装环境
Using cuda for inference.
Loads checkpoint by local backend from path: ./Musetalk/models/dwpose/dw-ll_ucoco_384.pth
MuseTalk导入失败，原因： Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found
使用MuseTalk前需要安装对应的环境
using safetensor as default
SadTalker 加载失败: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found
如果使用SadTalker，请先下载SadTalker模型
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
If you want use mossformer, lease install rotary_embedding_torch by: 
 pip install -U rotary_embedding_torch
WhisperASR 加载失败: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found
如果使用FunASR，请先下载WhisperASR模型并安装环境
Traceback (most recent call last):
  File "webui.py", line 952, in <module>
    gpu_memory = torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)  # Convert bytes to GB
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 395, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/root/miniconda3/lib/python3.8/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 500: named symbol not found
```

**Comment by Heaverno** [comment]
值得注意的是，一开始文件并没有出现在autodl-tmp里
```
root@8e103738cdd9:~# ls
Linly-Talker  autodl-pub  autodl-tmp  miniconda3  nltk_data  tf-logs
```

**Comment by Heaverno** [comment]
原因是nvidia-docker过时了，重启了一下装了nvidia-container-tookit就好了。但是CG客户端的jupyterlab又不能用了，还好CLI能用

**Comment by turndown** [comment]
> 值得注意的是，一开始文件并没有出现在autodl-tmp里
> 
> ```
> root@8e103738cdd9:~# ls
> Linly-Talker  autodl-pub  autodl-tmp  miniconda3  nltk_data  tf-logs
> ```

你好，请问下这个autodl-tmp挂载映射的是什么内容啊？我本来以为是把linly-talk的代码挂载到这里，但是我看启动的容器里已经有代码了，root/linly-talk就是代码。
另外如果我启动外部最新的代码autodl-tmp挂载，报错模型找不到错误比较多；
而直接启动容器自带的root/linly-talk，只报了edgetts模块错误。
启动的都是webui.py，我哪里操作有问题吗？
