### ISSUE TITLE
使用webui的问题

### ISSUE THREAD

**Issue by aa007shuai** [Kedreamix/Linly-Talker#115]
感谢作者提供的工具，我使用的AutoDL镜像直接创建的机器，直接运行python webui.py后，有几个报错，基本所有流程都不通，希望作者能回复下，感谢。

首先，一直报“EdgeTTS模型加载失败，请检查网络连接”，我看代码里的链接在服务器上是可以访问的，不知道什么原因一直加载失败。
其次，数字人实时对话的tab里面，使用PaddleTTS模型，输入问题，点击生成，报以下错误：
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1455, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/components/video.py", line 245, in postprocess
    self._format_subtitle(subtitle),
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/components/video.py", line 327, in _format_subtitle
    raise ValueError(
ValueError: Invalid value for parameter `subtitle`: ./results/avatars/yongen_musev/vid_output/res.mp4. Please choose a file with one of these extensions: ('.srt', '.vtt')

最后，在数字人多轮对话的tab里面，使用wav2lipv2+PaddleTTS，输入问题回复后，点生成报以下错误：
raceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1455, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/components/video.py", line 245, in postprocess
    self._format_subtitle(subtitle),
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/components/video.py", line 327, in _format_subtitle
    raise ValueError(
ValueError: Invalid value for parameter `subtitle`: results/result_voice_0e839839c0d948428dbf4d41ea2a1131.mp4. Please choose a file with one of these extensions: ('.srt', '.vtt')

**Comment by Kedreamix** [comment]
非常感谢你的关注，这其实是我的一个小bug，就是在返回值的时候少了一个括号，我会马上更新镜像以及代码，非常抱歉现在才回复你 @aa007shuai
