### ISSUE TITLE
webui  我是windows启动，请求指导

### ISSUE THREAD

**Issue by LionF-95** [Kedreamix/Linly-Talker#118]
Active code page: 65001

D:\workdirs\Linly-Talker-win\Linly-Talker-win>.\linly\python.exe webui.py
Traceback (most recent call last):
  File "D:\workdirs\Linly-Talker-win\Linly-Talker-win\webui.py", line 6, in <module>
    import torch, torchaudio
  File "D:\workdirs\Linly-Talker-win\Linly-Talker-win\linly\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "D:\workdirs\Linly-Talker-win\Linly-Talker-win\linly\lib\site-packages\torchaudio\_extension\__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "D:\workdirs\Linly-Talker-win\Linly-Talker-win\linly\lib\site-packages\torchaudio\_extension\utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "D:\workdirs\Linly-Talker-win\Linly-Talker-win\linly\lib\site-packages\torch\_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "D:\workdirs\Linly-Talker-win\Linly-Talker-win\linly\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\workdirs\Linly-Talker-win\Linly-Talker-win\linly\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

D:\workdirs\Linly-Talker-win\Linly-Talker-win>pause
Press any key to continue . . .

**Comment by Visien** [comment]
同样问题，这个包也存在，而且就在这个路径，但就是报错

**Comment by Visien** [comment]
解决了，torchaudio的版本问题，但audio的2.0.1不是官方推荐，直接都改2.1.0：
pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118

**Comment by Kedreamix** [comment]
感谢你的关注和回答，最近直接更新到2.4.1，用好一点的版本可能可以兼容更多的方法同时得到更好的效果
