### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by Dalongwang2025** [Kedreamix/Linly-Talker#26]
启动后报错了，总是解决不了，请问这是什么原因，该怎么解决？

(linly) D:\Linly-Talker>python app.py
Traceback (most recent call last):
  File "D:\Linly-Talker\app.py", line 5, in <module>
    from LLM import LLM
  File "D:\Linly-Talker\LLM\__init__.py", line 1, in <module>
    from .Linly import Linly
  File "D:\Linly-Talker\LLM\Linly.py", line 2, in <module>
    import torch
  File "C:\ProgramData\Anaconda3\envs\linly\lib\site-packages\torch\__init__.py", line 130, in <module>
    raise err
OSError: [WinError 127] 找不到指定的程序。 Error loading "C:\ProgramData\Anaconda3\envs\linly\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.

**Comment by Kedreamix** [comment]
这个应该是安装Pytorch以及CUDA的匹配问题
可以看看能不能正常使用pytorch
