### ISSUE TITLE
启动问题 执行python app.py出现如下的错误

### ISSUE THREAD

**Issue by anstonjie** [Kedreamix/Linly-Talker#31]
Traceback (most recent call last):
  File "D:\ai3\Linly-Talker\app.py", line 180, in <module>
    talker = SadTalker(lazy_load=True)
  File "D:\ai3\Linly-Talker\TFG\SadTalker.py", line 38, in __init__
    self.animate_from_coeff = AnimateFromCoeff(self.sadtalker_paths, self.device)
  File "D:\ai3\Linly-Talker\src\facerender\animate.py", line 82, in __init__
    self.load_cpk_mapping(sadtalker_path['mappingnet_checkpoint'], mapping=mapping)
  File "D:\ai3\Linly-Talker\src\facerender\animate.py", line 157, in load_cpk_mapping
    checkpoint = torch.load(checkpoint_path,  map_location=torch.device(device))
  File "D:\ai3\Linly-Talker\venv\lib\site-packages\torch\serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\ai3\Linly-Talker\venv\lib\site-packages\torch\serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by wufxgtihub123** [comment]
+1,我也遇到了同样的问题，

**Comment by Kedreamix** [comment]
这一部分是因为模型权重没有下载正确，可以重新下载模型权重放到指定位置尝试一下
