### ISSUE TITLE
Error of “python app.py”

### ISSUE THREAD

**Issue by geniuszxd** [Kedreamix/Linly-Talker#43]
(linlytalker) PS D:\Python\Linly-Talker>**python app_multi.py**
如果想使用FunASR，请先安装funasr，若使用Whisper，请忽略此条信息
PaddleTTS Error:  No module named 'paddlespeech'
如果使用PaddleTTS，请先安装PaddleTTS环境
pip install -r requirements_paddle.txt
ERNeRF导入失败，原因： No module named 'trimesh'
使用ERNeRF前需要安装对应的环境
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.23s/it]
using safetensor as default
Running on local URL:  https://127.0.0.1:7860
Traceback (most recent call last):
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_transports\default.py", line 69, in map_httpcore_exceptions
    yield
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_transports\default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpcore\_sync\connection_pool.py", line 216, in handle_request
    raise exc from None
  File "D:\Python\envs\linlytalker\lib\site-packages\httpcore\_sync\connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "D:\Python\envs\linlytalker\lib\site-packages\httpcore\_sync\http_proxy.py", line 317, in handle_request
    stream = stream.start_tls(**kwargs)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpcore\_sync\http11.py", line 383, in start_tls
    return self._stream.start_tls(ssl_context, server_hostname, timeout)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpcore\_backends\sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "D:\Python\envs\linlytalker\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Python\MetaHuman\Linly-Talker\app_multi.py", line 258, in <module>
    demo.launch(server_name=ip, # 本地端口localhost:127.0.0.1 全局端口转发:"0.0.0.0"
  File "D:\Python\envs\linlytalker\lib\site-packages\gradio\blocks.py", line 1946, in launch
    httpx.get(f"{self.local_url}startup-events", verify=ssl_verify)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_api.py", line 198, in get
    return request(
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_api.py", line 106, in request
    return client.request(
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_client.py", line 914, in send
    response = self._send_handling_auth(
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_transports\default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "D:\Python\envs\linlytalker\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "D:\Python\envs\linlytalker\lib\site-packages\httpx\_transports\default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)
(linlytalker) PS D:\Python\Linly-Talker>

请问是什么原因呢？ 我把模型文件都下载下来了，手动放到指定位置。那一系列的app_*.py的启动都报错，只有webui.py可以启动
我的cuda 11.7 python 3.10 pytorch 2.0.1

**Comment by geniuszxd** [comment]
哦可以了 发现问题了。用到互联网的资源，开了代理反而不行

**Comment by Kedreamix** [comment]
好的，好的，感谢你的关注
