### ISSUE TITLE
AttributeError: 'MuseTalk_RealTime' object has no attribute 'vae' 运行MuseTalk界面的时候 点击例子 运行一会儿就报下面的错误

### ISSUE THREAD

**Issue by anstonjie** [Kedreamix/Linly-Talker#53]
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "D:\ai3\Linly-Talker\TFG\MuseTalk.py", line 236, in prepare_material
    latents = self.vae.get_latents_for_unet(resized_crop_frame)
AttributeError: 'MuseTalk_RealTime' object has no attribute 'vae'

**Comment by anstonjie** [comment]
你好大佬就是怎么确认 先加载musetalk的模型，是不是执行python app_MuseTalk他不是自动加载吗

**Comment by Kedreamix** [comment]
这是我的问题，因为我稍微改了下代码，但是没有改muse的，我会在模型里面先加一个load_model

**Comment by Kedreamix** [comment]
已更新代码已解决，感谢你发现我的问题！

**Comment by anstonjie** [comment]
好的谢谢 我更新代码
