### ISSUE TITLE
AttributeError: 'MuseTalk_RealTime' object has no attribute 'vae' 开启后点击运行还是显示这个错误 

### ISSUE THREAD

**Issue by anstonjie** [Kedreamix/Linly-Talker#54]
![image](https://github.com/Kedreamix/Linly-Talker/assets/131445859/0b632a8f-09c8-4863-9946-ef4142ca9fc7)
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\linly\lib\site-packages\gradio\utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "D:\ai3\Linly-Talker\TFG\MuseTalk.py", line 236, in prepare_material
    latents = self.vae.get_latents_for_unet(resized_crop_frame)
AttributeError: 'MuseTalk_RealTime' object has no attribute 'vae'

**Comment by anstonjie** [comment]
没有问题了，确实是少了个括号，我加入了就可以了，辛苦大佬



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年06月20日 21:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Kedreamix/Linly-Talker] AttributeError: 'MuseTalk_RealTime' object has no attribute 'vae' 开启后点击运行还是显示这个错误  (Issue #54) |

我已测试没有问题，期待你的反馈

**Comment by Kedreamix** [comment]
好的，感谢你的反馈
