### ISSUE TITLE
MuseTalk 报错

### ISSUE THREAD

**Issue by XuankuF** [Kedreamix/Linly-Talker#60]
Hi, 我用的 v3.2 镜像，再用的MuseV Video Examples 生成视频，会报错：
```
因为纸质地图更直观、可靠，可快速查找特定位置，而智能手机应用程序则需要安装大量应用才能正常运行。
函数 TTS_response 运行时间： 2.7675397396087646 秒
函数 LLM_response 运行时间： 4.072483062744141 秒
answer.wav answer.vtt
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "/root/Linly-Talker/src/cost_time.py", line 7, in wrapper
    result = func(*args, **kwargs)
  File "/root/Linly-Talker/webui.py", line 457, in MuseTalker_response
    video = musetalker.inference_noprepare(driven_audio,
  File "/root/Linly-Talker/TFG/MuseTalk.py", line 327, in inference_noprepare
    os.makedirs(self.avatar_path+'/tmp',exist_ok =True)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by Ankitjaiswal1201** [comment]
How did you resolve this error?
