### ISSUE TITLE
win11 webui使用官方例子生成视频报EOFError，这个是edge-tts的问题吗

### ISSUE THREAD

**Issue by tiramisuBing** [Kedreamix/Linly-Talker#64]
为什么有些人选择使用纸质地图或寻求方向，而不是依赖GPS设备或智能手机应用程序？
'edge-tts' is not recognized as an internal or external command,
operable program or batch file.
函数 TTS_response 运行时间： 1.4796900749206543 秒
函数 LLM_response 运行时间： 1.4827227592468262 秒
using safetensor as default
{'checkpoint': 'checkpoints\\SadTalker_V0.0.2_256.safetensors', 'dir_of_BFM_fitting': 'src/config', 'audio2pose_yaml_path': 'src/config\\auido2pose.yaml', 'audio2exp_yaml_path': 'src/config\\auido2exp.yaml', 'pirender_yaml_path': 'src/config\\facerender_pirender.yaml', 'pirender_checkpoint': 'checkpoints\\epoch_00190_iteration_000400000_checkpoint.pt', 'use_safetensor': True, 'mappingnet_checkpoint': 'checkpoints\\mapping_00229-model.pth.tar', 'facerender_yaml': 'src/config\\facerender.yaml'}
D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\temp\b831c3f272bc2b8efa639cb0d376f563561d4c9e\full4.jpeg
landmark Det:: 100%|██████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.20steps/s]
3DMM Extraction In Video:: 100%|██████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.42steps/s]
./results/02761d07-17b8-4b68-901e-45b7f6702900\first_frame_dir\full4.mat ((450, 406), (0, 0, 450, 619), [0, 44.32542394004088, 450, 450])
Traceback (most recent call last):
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\librosa\core\audio.py", line 149, in load
    with sf.SoundFile(path) as sf_desc:
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening './results/02761d07-17b8-4b68-901e-45b7f6702900\\input\\answer.wav': Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\gradio\queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\gradio\blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\gradio\blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\gradio\utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\src\cost_time.py", line 7, in wrapper
    result = func(*args, **kwargs)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\webui.py", line 251, in Talker_response_img
    video = talker.test2(source_image,
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\TFG\SadTalker.py", line 277, in test2
    batch = get_data(first_coeff_path, audio_path, self.device, ref_eyeblink_coeff_path=ref_eyeblink_coeff_path, still=still_mode, \
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\src\generate_batch.py", line 63, in get_data
    wav = audio.load_wav(audio_path, 16000)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\src\utils\audio.py", line 10, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\librosa\core\audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\librosa\core\audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\audioread\__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\site-packages\audioread\rawread.py", line 62, in __init__
    self._file = aifc.open(self._fh)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\aifc.py", line 917, in open
    return Aifc_read(f)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\aifc.py", line 358, in __init__
    self.initfp(f)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\aifc.py", line 314, in initfp
    chunk = Chunk(file)
  File "D:\doc\Aimodel\Linly-Talker\Linly-Talker-win-all\linly\lib\chunk.py", line 63, in __init__
    raise EOFError
EOFError

**Comment by HenryBao91** [comment]
同样的错误，求问

**Comment by Kedreamix** [comment]
你好，这个在错误中可以看到`'edge-tts' is not recognized as an internal or external command,`这样的问题，这个属于在系统里面没有安装好edge-tts，这样的解决方法可以采用通过激活对应的环境以后，输入以下命令
`pip install edge-tts`

**Comment by 2twentyto2** [comment]
选取了paddletts还是报这种raise EOFError
EOFError和Format not recognised的错误
请问是什么原因
