### ISSUE TITLE
你好，在使用Musetalker的时候，报这个错误

### ISSUE THREAD

**Issue by xuquankun** [Kedreamix/Linly-Talker#88]
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1570, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/blocks.py", line 1455, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/components/video.py", line 245, in postprocess
    self._format_subtitle(subtitle),
  File "/root/miniconda3/lib/python3.8/site-packages/gradio/components/video.py", line 327, in _format_subtitle
    raise ValueError(
ValueError: Invalid value for parameter `subtitle`: ./results/avatars/2140087361/vid_output/res.mp4. Please choose a file with one of these extensions: ('.srt', '.vtt')

**Comment by Kedreamix** [comment]
你好，这个应该是有关于没有生成字幕的原因，不过我有更新，如果尝试后还出问题，可以给我更多的反馈

**Comment by Crescentz** [comment]
agmin

**Comment by gjw199513** [comment]
研究存在这个问题
