### ISSUE TITLE
huggingface 模型文件有缺失，请更新一下最新的模型文件

### ISSUE THREAD

**Issue by verigle** [Kedreamix/Linly-Talker#92]
下载了huggingface 中的模型文件后，运行时报各种缺少各种模型文件，
而使用modelscope 下载模型文件总是报错
```
2024-08-24 02:38:46,983 - modelscope - ERROR - File ./temp/tmpynv0dad3/llm.pt integrity check failed, the download may be incomplete, please try again.
```
希望能及时更新一下huggingface中的模型文件

**Comment by verigle** [comment]
从modelscope 下载的sadtalk 模型无法正常加载
```
SadTalker 加载失败: invalid load key, 'v'.
如果使用SadTalker，请先下载SadTalker模型

Using cuda for inference.
Loads checkpoint by local backend from path: ./Musetalk/models/dwpose/dw-ll_ucoco_384.pth
using safetensor as default
Traceback (most recent call last):
  File "webui.py", line 940, in <module>
    talker = SadTalker(lazy_load=True)
  File "/data2/projects/Kedreamix/Linly-Talker/TFG/SadTalker.py", line 37, in __init__
    self.animate_from_coeff = AnimateFromCoeff(self.sadtalker_paths, self.device)
  File "/data2/projects/Kedreamix/Linly-Talker/src/facerender/animate.py", line 82, in __init__
    self.load_cpk_mapping(sadtalker_path['mappingnet_checkpoint'], mapping=mapping)
  File "/data2/projects/Kedreamix/Linly-Talker/src/facerender/animate.py", line 157, in load_cpk_mapping
    checkpoint = torch.load(checkpoint_path,  map_location=torch.device(device))
  File "/root/anaconda3/envs/linly/lib/python3.8/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
  File "/root/anaconda3/envs/linly/lib/python3.8/site-packages/torch/serialization.py", line 1114, in load
    return _legacy_load(
  File "/root/anaconda3/envs/linly/lib/python3.8/site-packages/torch/serialization.py", line 1338, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

```

**Comment by verigle** [comment]
modelscope中依然缺失的模型文件：
NeRFTalk: checkpoints/hub/checkpoints/alexnet-owt-7be5be79.pth

**Comment by Kedreamix** [comment]
首先，NeRFTalk中的AlexNet应该会自动下载。接下来，我会定期更新Hugging Face 上的模型文件。Modelscope 中的 SadTalker 安装脚本形式应该也没有问题，否则您可以选择单独安装。请留意问题汇总部分。

**Comment by Kedreamix** [comment]
huggingface已经更新了
